#include<bits/stdc++.h>
using namespace std;

class Solution {
public:

    /*
        Given two strings ransomNote and magazine, return true if ransomNote can be constructed from magazine and false otherwise.

        Each letter in magazine can only be used once in ransomNote.
        
        example:
        Input: ransomNote = "a", magazine = "b"
        Output: false

        Input: ransomNote = "aa", magazine = "ab"
        Output: false

        Input: ransomNote = "aa", magazine = "aab"
        Output: true

    */

   bool canConstruct(string ransomNote, string magazine) {

        string s1, s2;
        int i, j, k;
        
        for(i = 0; i<magazine.length();i++)
    }

};